# _data/products.yml
- id: "p001"
  title: "HP Sauce"
  price: 50.00
  currency: "GBP"
  description: "HP Sauce Art Print."
  img: "/assets/images/HPSauce.jpg"
- id: "p002"
  title: "Black Bush"
  price: 50
  currency: "GBP"
  description: "Black Bush Whiskey Art Print."
  img: "/assets/images/BlackbushE.jpg"
